#!/bin/bash
# Script 2: FOSS Package Inspector
# Author: Arka Das
# Reg No: 24BOE10032

PACKAGE="python3"

echo "Checking if $PACKAGE is installed..."

if dpkg -l | grep -q $PACKAGE
then
    echo "$PACKAGE is installed."
    python3 --version
else
    echo "$PACKAGE is NOT installed."
fi

case $PACKAGE in
    python3)
        echo "Python: A powerful open-source programming language used worldwide."
        ;;
    git)
        echo "Git: Version control system used by developers."
        ;;
    firefox)
        echo "Firefox: Open-source web browser."
        ;;
    vlc)
        echo "VLC: Popular open-source media player."
        ;;
    *)
        echo "Unknown package."
        ;;
esac